# Generated by Django 3.2 on 2024-02-02 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20240202_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='reviews.category'),
            preserve_default=False,
        ),
    ]
